### PR TITLE
Cakephp 3.0 migration

### PR DESCRIPTION
**Pull request by nijel**

### CODE REVIEW

**Comment by smita786** [comment]
Hi Michal,

travis builds are now failing due to problems like connection timeout, authentication failure etc. Any idea why is it happening ? or How can we fix it ?
Scripts in .travis.yml is fixed per cake 3.0 as some of the jobs had passed in this build- https://travis-ci.org/phpmyadmin/error-reporting-server/builds/69087893, while others again errored due to connection timeout.

**Comment by smita786** [comment]
finally. travis build passed. 
Michal, can we merge it if it looks OK to you? :-)

**Comment by nijel** [comment]
Thanks!

**Comment by nijel** [comment]
Now deployed on production as well and seems to work really way faster than old code. Also I've reported some errors which I've found in the new code...

**Comment by smita786** [comment]
Thanks! :-) We'll need to setup cron job for stats to run on daily basis.

**Comment by nijel** [comment]
The cron job is there. But I had to disable following two jobs:

@hourly php error-reporting-server/app/webroot/cron_dispatcher.php /source_forge/sync_ticket_statuses
@weekly php error-reporting-server/app/webroot/cron_dispatcher.php /notifications/clean_old_notifs

The first one is probably not worth of fixing as we're moving out of sourceforge, but the latter one might be useful.

**Comment by smita786** [comment]
yeah Thanks, I'll write shell for clean_old_notifs (probably tonight) and 'll let you know the command to use for cron.

**Pull request merged**
