### PR TITLE
Add tests for shells

### PR DESCRIPTION
**Pull request by devenbansod**
This would help in increasing the code-coverage too.

Signed-off-by: Deven Bansod <devenbansod.bits@gmail.com>

### CODE REVIEW

**Comment by nijel** [comment]
...if the tests would work ;-)

**Comment by devenbansod** [comment]
Yeah. ;-) Already working on fixing them. 
I did not realise I have changed the Fixtures (which lead to other tests breaking). I just ran the new tests and pushed.

**Comment by devenbansod** [comment]
Some more changes required. Will fix them tomorrow.

**Comment by devenbansod** [comment]
Did not add the tests for Github-related shell. I will add tests for GithubController instead later (hopefully handled by mocking GithubApiComponent) which will cover that action.

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
