### PR TITLE
Move to more phpMyAdmin-like coding style

### PR DESCRIPTION
**Pull request by devenbansod**
* Move away from tab indentation to 4-spaces indentation
* Continue to move towards more phpMyAdmin-like coding style
* Continue moving Shells to phpMyAdmin-like coding style
* Continue moving Views to phpMyAdmin-like coding style

Signed-off-by: Deven Bansod <devenbansod.bits@gmail.com>

### CODE REVIEW

**Comment by nijel** [comment]
Thanks! Are you doing the changes manually or have you configured php-cs-fixer? The latter might be better approach in the long run (though I'm not sure how much it can fix).

**Comment by devenbansod** [comment]
I currently did part-manually and part by `phpcbf` with original [coding-standard](https://github.com/phpmyadmin/coding-standard).
But I will look into configuring the tool you mentioned. If it works, then that'd be great!

**Comment by nijel** [comment]
We're already using it for motranslator, shapefile and sql-parser, so you can base on the configuration there (though that is much closer to PSR than what we use at phpMyAdmin).

**Comment by devenbansod** [comment]
Thanks for the pointer.
I have made a new PR at #132 with the auto-fixes done by php-cs-fixer and have added a simiar config file to this repo (with changes to the folders to be fixed).

**Pull request merged**
