### PR TITLE
Send Email Notifications on newly added reports

### LINKED ISSUE #31: Provide email notification for new reports
Currently, new reports are not well handled. Having email notifications going to our bugs list might improve the situation.

### PR DESCRIPTION
**Pull request by devenbansod**
Send these notifications to developers@phpmyadmin.net

Fix #31

Signed-off-by: Deven Bansod <devenbansod.bits@gmail.com>

### CODE REVIEW

**Comment by nijel** [comment]
Is it possible to test email sending as well? Otherwise it looks good. 

Thought I'm not really sure if we want notifications for *all* reports on the devel list, maybe it would be better to have some summary mails or create separate list for these notifications.

**Comment by devenbansod** [comment]
We could have a cron job running once a week. The cron job would run a shell which sends emails for the reports added in the previous week. (We can may be limit number of reports in a mail to five/ten to prevent a very long mail and instead send them in parts). What do you think? 

I am okay with having a separate list for a trial and then we can decide later based on whether it is receiving too many email notifications per week.

**Comment by nijel** [comment]
I think we can start with code you've written on separate list, let's see how that works.

And what about the tests?

**Comment by devenbansod** [comment]
Yes. I will take a look on how we can test sending emails.

**Comment by devenbansod** [comment]
Hi @nijel, added the tests for sending email notifications.

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
