### PR TITLE
Use proper and complete JS script name while comparing to skip

### LINKED ISSUE #121: Wrong groupping of javascript incidents
Groupping of javascript incidents does group too many not matching incidents.

For example https://reports.phpmyadmin.net/reports/view/19421 "Syntax error, unrecognized expression: #Warnings&phpMyAdmin=toh1r7h6gn19tpqg7qn2hv3vfm6pg0ql" lists following incidents:
-  Cannot read property 'resize_handler' of null - https://reports.phpmyadmin.net/incidents/view/678550
-  null is not an object (evaluating 'event.data.resize_handler')  - https://reports.phpmyadmin.net/incidents/view/675909
-  cannot call methods on slider prior to initialization; attempted to call method 'value'  - https://reports.phpmyadmin.net/incidents/view/675536
-  Syntax error, unrecognized expression: #Warnings&phpMyAdmin=nbh8n82hfk4n3cqebhnhfi3sulkogj5c  - https://reports.phpmyadmin.net/incidents/view/674575

### PR DESCRIPTION
**Pull request by devenbansod**
Fix #121

Signed-off-by: Deven Bansod <devenbansod.bits@gmail.com>

### CODE REVIEW

**Comment by devenbansod** [comment]
Thanks for the review @nijel. I have fixed the tests.

**Comment by nijel** [comment]
I also wonder if we should not ignore *both* paths as this is obviously something which has been changed on the phpMyAdmin side, so old versions will still report the old path...

**Comment by devenbansod** [comment]
Did you mean 'if we should ~~not~~ ignore both paths' ?

**Comment by nijel** [comment]
Exactly :-). Though I didn't really look when it has been changed on the phpMyAdmin site, so maybe it's too old to care...

**Comment by devenbansod** [comment]
I checked it just now. 
It was changed in https://github.com/phpmyadmin/phpmyadmin/commit/addb363cdb86bfd3f2e89aa6a9ae254641225080 in mid-2013 (changes start from Release 4.1.0-alpha1). I guess it is too old to care now ?

**Comment by nijel** [comment]
Thanks for looking it up, then we probably don't have to care.

**Pull request merged**
