### PR TITLE
performamce improvement

### PR DESCRIPTION
**Pull request by smita786**
Hi,
This should improve performance of report landing page, report view page, incident page and notifications page. (all except Stats).
please do the following changes on server:
In app/Config/core.php, add following line
`define("BASE_DIR", "");`
In error reporting database, run following queries:
`ALTER TABLE incidents ADD INDEX (report_id);`
`create INDEX dev_report on notifications (developer_id, report_id);`

Signed-off-by: Smita Kumari <kumarismita62@gmail.com>

### CODE REVIEW

**Comment by nijel** [comment]
Can't the index creation be handled by schema migration?

**Comment by smita786** [comment]
@nijel yeah, let me add that in schema migration.

**Comment by smita786** [comment]
Hi Michal,

To add the index through migration, it first drop the column (on which index to be created) and then create column with index on that. 
So in this case we can't run the migration on production, as we will end up losing data for the column on which we are creating index. what should we do ? If we add a new migration file for index creation, we will need  to take data backup, run migration and then restore data. 
other option is add index in existing migration file where these tables(of which index column belong) are being created and run above commands directly on production.

**Comment by nijel** [comment]
It is not possibly to just add an index without touching the rest of table?

**Comment by smita786** [comment]
see https://github.com/phpmyadmin/error-reporting-server/blob/master/app/Plugin/Migrations/readme.md#alter-index , it says you need to drop the field first and then add index. Only the table on which we are adding index will be affected, others will not change.

**Comment by nijel** [comment]
Maybe we could use newer version of Cake to make this work?
http://book.cakephp.org/3.0/en/migrations.html

It's documentation explicitly mentions how to add new index migration:
bin/cake bake migration AddNameIndexToProducts name:string:index

-- 
	Michal Čihař | http://cihar.com | http://blog.cihar.com

**Comment by smita786** [comment]
yeah, ok, I'll try with newer version locally. lets see if it works :-).

**Pull request merged**
